### ISSUE TITLE
Computer Shader Optimization (Every fourth pixel)

### ISSUE THREAD

**Issue by klingerj** [mccannd/Project-Marshmallow#14]
Optimize the compute shader so that it only renders every fourth pixel (effectively renders at a quarter resolution each frame). Details in the 2015/2017 SIGGRAPH papers.

**Comment by mccannd** [comment]
I think this will cover it:
1. Make a uniform containing an int that cycles 0, 1, 2, 3. Call it **px**. It increments each time the compute is invoked.
2. When you invoke the compute, divide width and height by 2, invoking 1/4 as many threads.
3. In the shader to get UV: Multiply invocation by 2. Add 1 bit of **px** to x. Add 2 bit of **px** to y.
4. Similar for write target

Image filtering and post process should make it not too noticeable

Edit: will need to make a full reprojection kernel as discussed earlier. Maybe we can then lower this to 1/16 at a time, which the paper might be doing...

**Comment by mccannd** [comment]
Resolved 9bfda3cb112d7632685e68df8f33a1d94622cd00
